config/routes.rb
Rails.application.routes.draw do

  root 'welcome#landing'
  get 'свидания-без-слов', to: 'welcome#index'
  get 'svidanija-bez-slov', to: 'welcome#index', as: :real_root
  get 'foto-i-video-otchjoty-i-otzyvy-s-proshedshih-svidanij-bez-slov', to: 'recalls#index', as: :recalls
  get 'фото-и-видео-отчёты-и-отзывы-с-прошедших-свиданий-без-слов', to: 'recalls#index'



 

  
  resources :pages, only: [:edit, :update]
  get 'pravila-svidanij-bez-slov', to: 'pages#rules', as: :rules
  get 'правила-свиданий-без-слов', to: 'pages#rules'
  
  get 'statji', to: 'pages#entities', as: :entities
  get 'статьи', to: 'pages#entities'
  
  
  get 'gde-poznakomitsya', to: 'pages#where_to_meet', as: :where_to_meet
  get 'где-познакомиться', to: 'pages#where_to_meet'
  
  get 'gde-naiti-devushku', to: 'pages#where_to_find_a_girl', as: :where_to_find_a_girl
  get 'где-найти-девушку', to: 'pages#where_to_find_a_girl'
  
  get 'gde-naiti-parnya', to: 'pages#where_to_find_a_man', as: :where_to_find_a_man
  get 'где-найти-парня', to: 'pages#where_to_find_a_man'
  
  get 'vecherinki-znakomstva', to: 'pages#looking_for_party', as: :looking_for_party
  get 'вечеринки-знакомства', to: 'pages#looking_for_party'
  
  get 'bistrie-svidaniya', to: 'pages#speed_dating', as: :speed_dating
  get 'быстрые-свидания', to: 'pages#speed_dating'
  
  
  
  get 'chto-tebja-ozhidaet', to: 'pages#structure', as: :structure
  get 'что-тебя-ожидает', to: 'pages#structure'
  
  get 'informacionnaja-stranica', to: 'pages#info_page', as: :info_page
  get 'информационная-страница', to: 'pages#info_page'

  get 'o-zritelnom-kontakte', to: 'articles#index', as: :articles
  get 'о-зрительном-контакте', to: 'articles#index'
  resources :articles, except: :index

  get 'albomy/foto', to: 'albums#photo', as: :albums_photo
  get 'альбомы/фото', to: 'albums#photo'
  get 'albomy/video', to: 'albums#video', as: :albums_video
  get 'альбомы/видео', to: 'albums#video'

  resources :parties, except: [:index, :show]
  get 'parties', to: 'parties#index'
  get 'vecherinki', to: 'parties#index', as: :all_parties
  get 'вечеринки', to: 'parties#index'

  resources :requests, only: [:create, :destroy, :show]
  get 'podat-zajavku/:id', to: 'requests#new', as: :new_request
  get 'подать-заявку/:id', to: 'requests#new'
  get 'podat-zajavku', to: 'requests#new'
  get 'подать-заявку', to: 'requests#new'


  resources :recalls, except: :index
  get 'recalls_moderation', to: 'recalls#moderation', as: :recalls_moderation

  resources :photos, only: [:create, :destroy, :show]
  resources :photos, only: :update, format: 'json', defaults: { photoable_type: 'Photo' }
  resources :videos, only: [:edit, :update, :create, :destroy]

  post 'welcome/subscribe', to: 'welcome#subscribe', as: :subscribe

  devise_for :admins
  get 'admin', to: redirect('admins/sign_in')
  get 'zajavki', to: 'requests#index', as: :all_requests
  get 'заявки', to: 'requests#index'

  get 'oplata', to: 'payments#index', as: :payments
  get 'оплата', to: 'payments#index'

  post 'payments/pay_with_yandex_money', to: 'payments#pay_with_yandex_money', as: :pay_with_yandex_money
  post 'payments/pay_with_card', to: 'payments#pay_with_card', as: :pay_with_card
  get 'payments/code', to: 'payments#code'
  get 'payments/success', to: 'payments#success', as: :succeed_payment
  get 'payments/fail', to: 'payments#fail', as: :failed_payment
  # resources :payments, only: :create, format: 'html'
  # get 'результат-оплаты', to: 'payments#pay_result', constraints: { protocol: 'https' }

end

app/models/party.rb
# == Schema Information
#
# Table name: parties
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  address     :string(255)
#  ps          :text
#  date        :date
#  created_at  :datetime
#  updated_at  :datetime
#

class Party < ActiveRecord::Base

  validates :name, :description, :date, presence: true
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :ensure_signed_in, only: [:edit, :update, :destroy]
  before_action :set_party, only: [:edit, :update, :destroy]

  def index
    @parties = Party.all.order( 'date ASC' )
    @page = Page.where( name: '/parties' ).first
  end

  def new
    @party = Party.new
  end

  def edit
  end

  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to all_parties_path, notice: 'Вы успешно создали новую вечеринку.' }
        format.json { render :show, status: :created, location: all_parties_path }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to all_parties_path, notice: 'Информация о вечеринке была успешно обновлена.' }
        format.json { render :show, status: :ok, location: all_parties_path }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to all_parties_path, notice: 'Вы успешно удалили вечеринку.' }
      format.json { head :no_content }
    end
  end

  private
    def set_party
      @party = Party.find(params[:id])
    end

    def party_params
      params.require(:party).permit( :name, :description, :address, :ps, :date )
    end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.haml
= simple_form_for @party do |f|
  - if @party.errors.any?
    #error_explanation
      %span
        %h2 При заполнении формы обнаружены следующие ошибки:
      %ul
        - @party.errors.full_messages.each do |message|
          %li= message
  = f.text_field :name, placeholder: 'Введите название вечеринки...'
  = f.text_area :description, placeholder: 'Опишите вечеринку...', class: 'tinymce'
  = tinymce
  = f.text_field :address, placeholder: 'Введите адрес...'
  = f.text_field :ps, placeholder: 'Укажите пункт P.S. ...'
  = f.input :date, as: :datepicker, placeholder: 'Выберите дату...', label: false
  .actions
    = f.submit @party.new_record? && 'Создать вечеринку' || 'Обновить информацию'
    - unless @party.new_record?
      .delete= link_to 'Удалить вечеринку', party_path(@party), method: :delete

app/views/parties/edit.html.haml
%h1 Редактирование вечеринки
= render 'form'

.admin-links
  = link_to 'Вернуться на страницу всех вечеринок', all_parties_path

app/views/parties/index.html.haml
- provide :title, 'Вечеринки'

.parties
  .content
    = render 'layouts/page_description'
    .parties-container
      - @parties.each do |party|
        .party
          %span
            %h2.title= party.name
          .description-party= party.description.html_safe
          - if party.address?
            .address
              .title Адрес:
              = party.address
          - if party.ps?
            .ps
              .title P.S.:
              = party.ps
          .foot
            .structure-rules
              .structure
                = link_to structure_path do
                  Структура
                  %br Свиданий без Слов
              .separator
              .rules
                = link_to rules_path do
                  Ознакомиться с правилами
                  %br Свиданий без Слов
            .become-member= link_to 'Подать заявку', new_request_path( party )
          - if admin_signed_in?
            .admin-sub-links
              = link_to 'Редактировать информацию', edit_party_path( party )
    .money-back
      .title Гарантия возврата денег
      .ps
        %p
          %span.left
          .text
            Если ты посчитаешь что зря потратил время и больше не захочешь становиться участником вечеринок Свидания Без Слов, мы вернём тебе 100% стоимость твоего билета без лишних вопросов в течении двух дней после вечеринки (
            .yellow
              при условии твоего участия на ней
            ).
    - if admin_signed_in?
      .admin-links
        = link_to 'Создать вечеринку', new_party_path
  = render 'layouts/sidebar_only_group'

app/views/parties/new.html.haml
.content
  %h1 Создание новой вечеринки
  = render 'form'
  .admin-links
    = link_to 'Назад ко всем вечеринкам', all_parties_path