config/routes.rb
Rails.application.routes.draw do

  root 'welcome#landing'
  get 'свидания-без-слов', to: 'welcome#index'
  get 'svidanija-bez-slov', to: 'welcome#index', as: :real_root
  get 'foto-i-video-otchjoty-i-otzyvy-s-proshedshih-svidanij-bez-slov', to: 'recalls#index', as: :recalls
  get 'фото-и-видео-отчёты-и-отзывы-с-прошедших-свиданий-без-слов', to: 'recalls#index'



 

  
  resources :pages, only: [:edit, :update]
  get 'pravila-svidanij-bez-slov', to: 'pages#rules', as: :rules
  get 'правила-свиданий-без-слов', to: 'pages#rules'
  
  get 'statji', to: 'pages#entities', as: :entities
  get 'статьи', to: 'pages#entities'
  
  
  get 'gde-poznakomitsya', to: 'pages#where_to_meet', as: :where_to_meet
  get 'где-познакомиться', to: 'pages#where_to_meet'
  
  get 'gde-naiti-devushku', to: 'pages#where_to_find_a_girl', as: :where_to_find_a_girl
  get 'где-найти-девушку', to: 'pages#where_to_find_a_girl'
  
  get 'gde-naiti-parnya', to: 'pages#where_to_find_a_man', as: :where_to_find_a_man
  get 'где-найти-парня', to: 'pages#where_to_find_a_man'
  
  get 'vecherinki-znakomstva', to: 'pages#looking_for_party', as: :looking_for_party
  get 'вечеринки-знакомства', to: 'pages#looking_for_party'
  
  get 'bistrie-svidaniya', to: 'pages#speed_dating', as: :speed_dating
  get 'быстрые-свидания', to: 'pages#speed_dating'
  
  
  
  get 'chto-tebja-ozhidaet', to: 'pages#structure', as: :structure
  get 'что-тебя-ожидает', to: 'pages#structure'
  
  get 'informacionnaja-stranica', to: 'pages#info_page', as: :info_page
  get 'информационная-страница', to: 'pages#info_page'

  get 'o-zritelnom-kontakte', to: 'articles#index', as: :articles
  get 'о-зрительном-контакте', to: 'articles#index'
  resources :articles, except: :index

  get 'albomy/foto', to: 'albums#photo', as: :albums_photo
  get 'альбомы/фото', to: 'albums#photo'
  get 'albomy/video', to: 'albums#video', as: :albums_video
  get 'альбомы/видео', to: 'albums#video'

  resources :parties, except: [:index, :show]
  get 'parties', to: 'parties#index'
  get 'vecherinki', to: 'parties#index', as: :all_parties
  get 'вечеринки', to: 'parties#index'

  resources :requests, only: [:create, :destroy, :show]
  get 'podat-zajavku/:id', to: 'requests#new', as: :new_request
  get 'подать-заявку/:id', to: 'requests#new'
  get 'podat-zajavku', to: 'requests#new'
  get 'подать-заявку', to: 'requests#new'


  resources :recalls, except: :index
  get 'recalls_moderation', to: 'recalls#moderation', as: :recalls_moderation

  resources :photos, only: [:create, :destroy, :show]
  resources :photos, only: :update, format: 'json', defaults: { photoable_type: 'Photo' }
  resources :videos, only: [:edit, :update, :create, :destroy]

  post 'welcome/subscribe', to: 'welcome#subscribe', as: :subscribe

  devise_for :admins
  get 'admin', to: redirect('admins/sign_in')
  get 'zajavki', to: 'requests#index', as: :all_requests
  get 'заявки', to: 'requests#index'

  get 'oplata', to: 'payments#index', as: :payments
  get 'оплата', to: 'payments#index'

  post 'payments/pay_with_yandex_money', to: 'payments#pay_with_yandex_money', as: :pay_with_yandex_money
  post 'payments/pay_with_card', to: 'payments#pay_with_card', as: :pay_with_card
  get 'payments/code', to: 'payments#code'
  get 'payments/success', to: 'payments#success', as: :succeed_payment
  get 'payments/fail', to: 'payments#fail', as: :failed_payment
  # resources :payments, only: :create, format: 'html'
  # get 'результат-оплаты', to: 'payments#pay_result', constraints: { protocol: 'https' }

end

app/views/pages/_form.html.haml
= simple_form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      %span
        %h2 При заполнении формы обнаружены следующие ошибки:
      %ul
        - @page.errors.full_messages.each do |message|
          %li= message
  = f.text_field :title, placeholder: 'Заголовок...'
  = f.text_area :content, placeholder: 'Страница...', class: 'tinymce'
  = f.text_area :ps, placeholder: 'Последний пункт с вертикальной чертой...', class: 'tinymce' unless /^\/$/ =~ @page.name
  = f.text_field :sidebar_title, placeholder: 'Заголовок для сайдбара...' if /^\/$|^\/свидания-без-слов$/ =~ @page.name
  = f.text_field :meta_description, placeholder: 'Поле description для SEO...'
  = tinymce
  .actions
    = f.submit 'Обновить информацию'

app/views/pages/edit.html.haml
%h1 Редактирование страницы
= render 'form'

.admin-links
  = link_to 'Вернуться назад', :back

app/views/pages/entities.html.haml
- provide :title, @page.title

.sctructure
	.content
		= render 'layouts/page_description'
		.entity-button= link_to 'Где познакомиться', where_to_meet_path
		.entity-button= link_to 'Где найти девушку', where_to_find_a_girl_path
		.entity-button= link_to 'Где найти парня', where_to_find_a_man_path
		.entity-button= link_to 'Вечеринки знакомства', looking_for_party_path
		.entity-button= link_to 'Быстрые свидания', speed_dating_path

app/views/pages/info_page.html.haml
- provide :title, @page.title

.structure
  .content
    = render 'layouts/page_description'

app/views/pages/looking_for_party.html.haml
- provide :title, @page.title

.sctructure
	.content
		<h1>Вечеринки знакомства помогут найти судьбу</h1>
		<p>Одним из самых интересных и популярных способов найти свою вторую половинку уже давно стали <b>вечеринки знакомства</b>. Это уникальные мероприятия призваны соединить одинокие сердца. Санкт-Петербург предлагает широкий выбор возможностей. Какими же бывают вечера для желающих познакомиться:</p>
		<p>•	Быстрые свидания. Довольно известное и новомодное течение. Вы приходите в уютное кафе и общаетесь с массой собеседников. При этом времени у вас по 2 минуты на каждого из них. Но узнать человека за столь короткий срок практически невозможно.</p>
		<p>•	Тематические мероприятия. Такие <b>вечеринки знакомства</b> редко заканчиваются успехом, ведь довольно часто хорошие люди отличаются робостью и просто стесняются подойти первыми.</p>
		<p>•	Свидания вслепую. Обычно они происходят через интернет. Но стоит помнить, что фотографии и описания собственной внешности и качеств часто оказываются приукрашенными.</p>
		<p>•	Свидания без слов. Это абсолютно новый, но стремительно набирающий популярность, метод поиска своей пары. Данные <b>вечеринки знакомства</b> отличаются своей искренностью, ведь именно здесь, вы получаете шанс заглянуть собеседнику прямо в душу, увидеть его мотивы и качества.</p>
		<p>«Свидания без слов» – лучший способ встретить искреннего и настоящего человека. К чему разговоры? Достаточно одного взгляда.</p>

app/views/pages/rules.html.haml
- provide :title, 'Правила'
- js 'pages'

.rules
  .content
    = render 'layouts/page_description'

  = render 'layouts/sidebar_only_group'

app/views/pages/speed_dating.html.haml
- provide :title, @page.title

.sctructure
	.content
		<h1>Быстрые свидания – оптимальное решение личных проблем</h1>
		<p>Speed-dating или <b>быстрые свидания</b> – это уникальный способ максимально быстро познакомиться с достаточно большим количеством новых людей. Они часто помогают завести друзей, найти пару на вечер или на всю жизнь.</p>
		<p>Вечеринка проходит в стиле беседы. Но только лица за столиком довольно быстро сменяют друг друга. Вы можете шутить, смеяться, говорить правду или врать – делайте что угодно, чтобы узнать нового собеседника за столом. Такие <b>быстрые свидания</b> – расширяют круг знакомств. Но помогут ли она найти вторую половинку? Шансы не слишком велики. Хотя они есть всегда.</p>
		<p>Есть и второй способ спид-дэйтинга – свидания без слов. Это абсолютно новое течение, организованное людьми, которые устали от притворства и лжи. Они хотят видеть суть и намерения человека сразу. Мало кто, скрывая что-либо, согласится смотреть собеседнику прямо в глаза на протяжении нескольких минут.</p>
		<p>Глаза – это зеркало души. В них вы легко найдете правду и ответы на все ваши вопросы. Сможете достучаться до самых глубоких струн души. Такие <b>быстрые свидания</b> часто дают толчок к зарождению новых отношений, открывают собеседнику истинное лицо, показывают все тайное, помогают раскрыться.</p>
		<p>Свидания без слов – это лучший способ начать искренние и настоящие отношения.</p>

app/views/pages/structure.html.haml
- provide :title, 'Что тебя ожидает'

.structure
  .content
    = render 'layouts/page_description'

  = render 'layouts/sidebar_only_group'

app/views/pages/where_to_find_a_girl.html.haml
- provide :title, @page.title

.sctructure
	.content
		<h1>Где найти девушку для серьезных отношений</h1>
		<p>Современные девушки всегда прекрасно выглядят, и познакомиться с ними стремится каждый парень. Но довольно часто, симпатичное личико таит за собой коварную и расчетливую дамочку. При первом же взгляде она оценивает ваш гардероб и уже точно знает: соответствуете вы ее потребностям или нет. Так, <b>где найти девушку</b>, которая сможет ответить взаимностью искренне, а, не исходя из ваших финансовых возможностей? Чаровницу, которая покорит открытостью и тем, что она настоящая? Конечно же, на «Свидании без слов».</p>
		<p>Только здесь, вы сможете заглянуть человеку в глаза. Вам не нужно стыдливо прятать взгляд или отводить его. Только здесь, вы познаете настоящую свободу общения – беседу без слов. Только глаза в глаза, в полной тишине и с приглушенным светом.</p>
		<p>Только здесь, вопрос: <b>где найти девушку</b>, которая очарует искренней улыбкой, перестает быть актуальным. Потому что вот она, сидит перед вами, немного стесняясь и открывая самые тайные закоулки своей души именно вам. Достаточно просто заглянуть в глаза, и вы все увидите: усталость, простоту, загадку и надежду. Возможно, вам повезет, и во взгляде вы прочитаете симпатию.</p>
		<p>Петербург - большой город, он манит богемной жизнью и гламуром, но не этого жаждет душа. Каждый хочет встретить близкого по духу человека. <b>Где найти девушку</b> или парня? Конечно же, на свидании без слов.</p>

app/views/pages/where_to_find_a_man.html.haml
- provide :title, @page.title

.sctructure
	.content
		<h1>Где найти парня в Питере</h1>
		<p>Многие девушки Петербурга задаются вопросом: <b>где найти парня</b>? Но не просто так, а чтобы честного и открытого. Но молодые люди, с которыми они обычно начинают общение на улицах города или в модных заведениях, редко оправдывают надежды. Мало того, такие знакомства часто заканчиваются разочарованием, ведь внешняя привлекательность не гарантирует появления более высоких чувств.</p>
		<p>Многие посещают быстрые свидания, но на них редко можно встретить приятного собеседника, при этом многие ищут «пару на вечер», а не серьезных отношений. Ведь мест, <b>где найти парня</b> для мимолетного увлечения, так много.</p>
		<p>Другое дело – поиск с серьезными целями. Ведь так хочется тепла и любви, которая будет длиться не один месяц. Для этого важно узнать собеседника, постичь его суть – заглянуть в душу.</p>
		<p>Оптимальным способом для знакомства и решением проблемы «<b>где найти парня</b>», являются «Свидания без слов». Только здесь, собеседник не сможет скрыться за мишурой красивых фраз. Говорить будут только глаза. Вы наконец-то осознаете, что такое настоящая симпатия, ведь одного взгляда вполне достаточно, чтобы влюбиться.</p>
		<p>Свидания без слов – это лучший способ скоротать вечер в приятной компании. Мало ли, вдруг именно здесь вы встретите свою судьбу?</p>

app/views/pages/where_to_meet.html.haml
- provide :title, @page.title

.sctructure
	.content
		<h1>Где познакомиться в Санкт-Петербурге</h1>
		<p>Питер достаточно большой город и мест, <b>где познакомиться</b> с представителями противоположного пола, большое множество. Но такие встречи и попытки найти родную душу редко заканчиваются успехом, ведь общение всегда таит в себе подтекст, скрывающий истинные мотивы собеседника.</p>
		<p>Вы устали от бесконечных и бессмысленных свиданий с людьми, которые только и думают о количестве покоренных сердец? Значит, хватит болтать – пора заглянуть собеседнику в глаза. Важно не просто смотреть, а увидеть суть и осознать, без лишних слов и пафоса, кто перед вами, интересно ли вам продолжение общения.</p>
		<p>Для того, чтобы понять, <b>где познакомиться</b> с людьми, которые так же, как и вы устали от бессмысленной суеты и быстрого течения времени, достаточно сходить на «Свидание без слов». Только здесь, перед вами откроется возможность увидеть истинное лицо собеседника, который не сможет спрятаться за водопадом слов.</p>
		<p>Всего полторы минуты и вы узнаете о человеке практически все. Всего полторы минуты дадут больше информации, чем годы общения. Всего две минуты и вы увидите все тайное, эмоции и чувства собеседника.</p>
		<p>Если вы ищете серьезных отношений, то теперь вопрос о том, <b>где познакомиться</b> с интересным человеком, решен. «Свидание без слов» – ваш шанс познакомиться.</p>