config/routes.rb
Rails.application.routes.draw do

  root 'welcome#landing'
  get 'свидания-без-слов', to: 'welcome#index'
  get 'svidanija-bez-slov', to: 'welcome#index', as: :real_root
  get 'foto-i-video-otchjoty-i-otzyvy-s-proshedshih-svidanij-bez-slov', to: 'recalls#index', as: :recalls
  get 'фото-и-видео-отчёты-и-отзывы-с-прошедших-свиданий-без-слов', to: 'recalls#index'



 

  
  resources :pages, only: [:edit, :update]
  get 'pravila-svidanij-bez-slov', to: 'pages#rules', as: :rules
  get 'правила-свиданий-без-слов', to: 'pages#rules'
  
  get 'statji', to: 'pages#entities', as: :entities
  get 'статьи', to: 'pages#entities'
  
  
  get 'gde-poznakomitsya', to: 'pages#where_to_meet', as: :where_to_meet
  get 'где-познакомиться', to: 'pages#where_to_meet'
  
  get 'gde-naiti-devushku', to: 'pages#where_to_find_a_girl', as: :where_to_find_a_girl
  get 'где-найти-девушку', to: 'pages#where_to_find_a_girl'
  
  get 'gde-naiti-parnya', to: 'pages#where_to_find_a_man', as: :where_to_find_a_man
  get 'где-найти-парня', to: 'pages#where_to_find_a_man'
  
  get 'vecherinki-znakomstva', to: 'pages#looking_for_party', as: :looking_for_party
  get 'вечеринки-знакомства', to: 'pages#looking_for_party'
  
  get 'bistrie-svidaniya', to: 'pages#speed_dating', as: :speed_dating
  get 'быстрые-свидания', to: 'pages#speed_dating'
  
  
  
  get 'chto-tebja-ozhidaet', to: 'pages#structure', as: :structure
  get 'что-тебя-ожидает', to: 'pages#structure'
  
  get 'informacionnaja-stranica', to: 'pages#info_page', as: :info_page
  get 'информационная-страница', to: 'pages#info_page'

  get 'o-zritelnom-kontakte', to: 'articles#index', as: :articles
  get 'о-зрительном-контакте', to: 'articles#index'
  resources :articles, except: :index

  get 'albomy/foto', to: 'albums#photo', as: :albums_photo
  get 'альбомы/фото', to: 'albums#photo'
  get 'albomy/video', to: 'albums#video', as: :albums_video
  get 'альбомы/видео', to: 'albums#video'

  resources :parties, except: [:index, :show]
  get 'parties', to: 'parties#index'
  get 'vecherinki', to: 'parties#index', as: :all_parties
  get 'вечеринки', to: 'parties#index'

  resources :requests, only: [:create, :destroy, :show]
  get 'podat-zajavku/:id', to: 'requests#new', as: :new_request
  get 'подать-заявку/:id', to: 'requests#new'
  get 'podat-zajavku', to: 'requests#new'
  get 'подать-заявку', to: 'requests#new'


  resources :recalls, except: :index
  get 'recalls_moderation', to: 'recalls#moderation', as: :recalls_moderation

  resources :photos, only: [:create, :destroy, :show]
  resources :photos, only: :update, format: 'json', defaults: { photoable_type: 'Photo' }
  resources :videos, only: [:edit, :update, :create, :destroy]

  post 'welcome/subscribe', to: 'welcome#subscribe', as: :subscribe

  devise_for :admins
  get 'admin', to: redirect('admins/sign_in')
  get 'zajavki', to: 'requests#index', as: :all_requests
  get 'заявки', to: 'requests#index'

  get 'oplata', to: 'payments#index', as: :payments
  get 'оплата', to: 'payments#index'

  post 'payments/pay_with_yandex_money', to: 'payments#pay_with_yandex_money', as: :pay_with_yandex_money
  post 'payments/pay_with_card', to: 'payments#pay_with_card', as: :pay_with_card
  get 'payments/code', to: 'payments#code'
  get 'payments/success', to: 'payments#success', as: :succeed_payment
  get 'payments/fail', to: 'payments#fail', as: :failed_payment
  # resources :payments, only: :create, format: 'html'
  # get 'результат-оплаты', to: 'payments#pay_result', constraints: { protocol: 'https' }

end

app/models/recall.rb
# == Schema Information
#
# Table name: recalls
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  email        :string(255)
#  text         :text
#  published    :boolean
#  created_at   :datetime
#  updated_at   :datetime
#  published_at :datetime
#

class Recall < ActiveRecord::Base
  validates :name, :email, :text, presence: true

  scope :published, -> { where published: true }

  self.per_page = 10

  before_save :set_published_at, if: Proc.new { |recall| recall.published == true }

  protected

    def set_published_at
      self.published_at = Time.current
    end
end

app/controllers/recalls_controller.rb
class RecallsController < ApplicationController
  before_action :ensure_signed_in, except: [:index, :create]
  before_action :set_page, only: [:index]

  def index
    @recalls = Recall.paginate( page: params[:page] ).order('published_at DESC').published
    @recall = Recall.new
    @photo_last = Photo.where( photoable_type: 'Photo' ).last

    @video_last = Video.all_but_main_and_landing.last
    # @video_last = Photo.where( photoable_type: 'Video' ).last
  end


  def create
    @recall = Recall.new(recall_params)

    respond_to do |format|
      if @recall.save
        format.html { redirect_to :back, notice: 'Твой отзыв получен. После проверки модератором он будет опубликован.' }
        format.json { render :show, status: :created, location: :back }
      else
        format.html { render :back }
        format.json { render json: @recall.errors, status: :unprocessable_entity }
      end
    end
  end

  def moderation
    @recalls = Recall.order( 'published_at DESC' ).all
  end

  def show
    respond_to do |format|
      format.json {
        render json: Recall.select(:id, :text).find( params[:id] )
      }
    end
  end

  def update
    recall = Recall.find( params[:id] )
    respond_to do |format|
      if recall.update( recall_update_params )
        format.json { render json: { status: 'recall-updated', status_text: 'Обновление отзыва произошло успешно.', date: recall.published_at.strftime("%d.%m.%y") } }
      else
        format.json { render json: { status: 'error', status_text: 'При обновлении отзыва произошла ошибка.' } }
      end
    end
  end

  def destroy
    recall = Recall.destroy( params[:id] )
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

    def set_page
      @page = Page.where( name: '/фото-и-видео-отчёты-и-отзывы-с-прошедших-свиданий-без-слов' ).take
    end

    def recall_params
      params.require(:recall).permit(:name, :email, :text)
    end

    def recall_update_params
      params.require(:recall).permit(:published_at, :published)
    end
end

app/helpers/recalls_helper.rb
module RecallsHelper
end

app/views/recalls/index.html.haml
- provide :title, 'Фото и видео отчёты с прошедших Свиданий без Слов'

.recalls
  .content
    = render 'layouts/page_description'
    .clear
    .album-container.photo-album
      .album
        = link_to albums_photo_path do
          = image_tag @photo_last.photo_url(:site, :album_thumb) unless @photo_last.nil?
          .photo-icon.icon
          .title ФОТО
          .watch смотреть
          .foot Фото со Свиданий без Слов
      .last-update
        Последнее добавление:
        %br= @photo_last.created_at.strftime("%d.%m.%y") unless @photo_last.nil?
    .album-container.video-album
      .album
        = link_to albums_video_path do
          = image_tag @video_last.photo.photo_url(:site, :album_thumb) if !@video_last.nil? && @video_last.try(:photo)
          .video-icon.icon
          .title ВИДЕО
          .watch смотреть
          .foot
            Видео со свиданий без Слов +
            .i эмоции участников после вечеринки
      .last-update
        Последнее добавление:
        %br= @video_last.created_at.strftime("%d.%m.%y") unless @video_last.nil?
    .clear
    %span
      %h2.recalls-title Отзывы
    .how-is-it Как это... Смотреть в глаза...
    .recalls-content
      - if @recalls.empty?
        .recall
          Отзывов пока нет.
      - else
        - @recalls.each do |r|
          .recall
            .name-date
              .name= r.name
              .date= r.published_at.strftime( "%d.%m.%y" )
            .text= r.text
        .clear
        = will_paginate @recalls
    .clear
    = simple_form_for @recall, url: 'recalls', html: { class: 'guest-form' } do |r|
      .title Оставить свой отзыв:
      = r.input :name, placeholder: 'Имя', label: 'обязательно'
      .clear
      = r.input :email, placeholder: 'E-mail', label: 'обязательно'
      .clear
      = r.input :text, as: :text, placeholder: 'Твой отзыв...', label: false
      .clear
      .actions
        .disclaimer * комментарий проверяется модератором
        = r.submit 'Опубликовать'
    - if admin_signed_in?
      .admin-links= link_to 'Модерировать отзывы', recalls_moderation_path
  = render 'layouts/sidebar_only_group'

app/views/recalls/moderation.html.haml
- provide :title, 'Модерация отзывов'

.recalls.recalls-moderation
  .content
    .description-main
      %h1.title Модерация отзывов
    .recalls-list
      .head
        .num #
        .name Имя
        .email E-mail
        .date Дата
        .published Опубликовано
        .delete
      .body
        - @recalls.each_with_index do |r,i|
          .recall
            = link_to recall_path( r.id ), remote: true, data: { type: 'json' }, class: 'show' do
              .num= i + 1
              .name= r.name
              .email= r.email
            .date{ data: { id: r.id } }
              = r.published_at.present? && r.published_at.strftime( "%d.%m.%y" ) || 'Новый'
            .published
              = check_box_tag :published, 'true', r.published
              = hidden_field_tag :recall_id, r.id
            .delete
              = link_to recall_path( r.id ), remote: true, method: :delete, data: { type: 'json', confirm: 'Ты точно хочешь удалить этот отзыв?' }, class: 'delete' do
                .close-small
                  .x
                  .y
        .admin-links
          Всего отзывов:
          = @recalls.count
    .clear
    .admin-links= link_to 'Вернуться на страницу отзывов', recalls_path

  = render 'layouts/sidebar_only_group'