config/routes.rb
Rails.application.routes.draw do

  root 'welcome#landing'
  get 'свидания-без-слов', to: 'welcome#index'
  get 'svidanija-bez-slov', to: 'welcome#index', as: :real_root
  get 'foto-i-video-otchjoty-i-otzyvy-s-proshedshih-svidanij-bez-slov', to: 'recalls#index', as: :recalls
  get 'фото-и-видео-отчёты-и-отзывы-с-прошедших-свиданий-без-слов', to: 'recalls#index'



 

  
  resources :pages, only: [:edit, :update]
  get 'pravila-svidanij-bez-slov', to: 'pages#rules', as: :rules
  get 'правила-свиданий-без-слов', to: 'pages#rules'
  
  get 'statji', to: 'pages#entities', as: :entities
  get 'статьи', to: 'pages#entities'
  
  
  get 'gde-poznakomitsya', to: 'pages#where_to_meet', as: :where_to_meet
  get 'где-познакомиться', to: 'pages#where_to_meet'
  
  get 'gde-naiti-devushku', to: 'pages#where_to_find_a_girl', as: :where_to_find_a_girl
  get 'где-найти-девушку', to: 'pages#where_to_find_a_girl'
  
  get 'gde-naiti-parnya', to: 'pages#where_to_find_a_man', as: :where_to_find_a_man
  get 'где-найти-парня', to: 'pages#where_to_find_a_man'
  
  get 'vecherinki-znakomstva', to: 'pages#looking_for_party', as: :looking_for_party
  get 'вечеринки-знакомства', to: 'pages#looking_for_party'
  
  get 'bistrie-svidaniya', to: 'pages#speed_dating', as: :speed_dating
  get 'быстрые-свидания', to: 'pages#speed_dating'
  
  
  
  get 'chto-tebja-ozhidaet', to: 'pages#structure', as: :structure
  get 'что-тебя-ожидает', to: 'pages#structure'
  
  get 'informacionnaja-stranica', to: 'pages#info_page', as: :info_page
  get 'информационная-страница', to: 'pages#info_page'

  get 'o-zritelnom-kontakte', to: 'articles#index', as: :articles
  get 'о-зрительном-контакте', to: 'articles#index'
  resources :articles, except: :index

  get 'albomy/foto', to: 'albums#photo', as: :albums_photo
  get 'альбомы/фото', to: 'albums#photo'
  get 'albomy/video', to: 'albums#video', as: :albums_video
  get 'альбомы/видео', to: 'albums#video'

  resources :parties, except: [:index, :show]
  get 'parties', to: 'parties#index'
  get 'vecherinki', to: 'parties#index', as: :all_parties
  get 'вечеринки', to: 'parties#index'

  resources :requests, only: [:create, :destroy, :show]
  get 'podat-zajavku/:id', to: 'requests#new', as: :new_request
  get 'подать-заявку/:id', to: 'requests#new'
  get 'podat-zajavku', to: 'requests#new'
  get 'подать-заявку', to: 'requests#new'


  resources :recalls, except: :index
  get 'recalls_moderation', to: 'recalls#moderation', as: :recalls_moderation

  resources :photos, only: [:create, :destroy, :show]
  resources :photos, only: :update, format: 'json', defaults: { photoable_type: 'Photo' }
  resources :videos, only: [:edit, :update, :create, :destroy]

  post 'welcome/subscribe', to: 'welcome#subscribe', as: :subscribe

  devise_for :admins
  get 'admin', to: redirect('admins/sign_in')
  get 'zajavki', to: 'requests#index', as: :all_requests
  get 'заявки', to: 'requests#index'

  get 'oplata', to: 'payments#index', as: :payments
  get 'оплата', to: 'payments#index'

  post 'payments/pay_with_yandex_money', to: 'payments#pay_with_yandex_money', as: :pay_with_yandex_money
  post 'payments/pay_with_card', to: 'payments#pay_with_card', as: :pay_with_card
  get 'payments/code', to: 'payments#code'
  get 'payments/success', to: 'payments#success', as: :succeed_payment
  get 'payments/fail', to: 'payments#fail', as: :failed_payment
  # resources :payments, only: :create, format: 'html'
  # get 'результат-оплаты', to: 'payments#pay_result', constraints: { protocol: 'https' }

end

app/views/layouts/_footer.html.haml
%footer
  .foot
    .bg
    .info
      .copyright-email
        .copyright Свидания без слов &copy; 2014
        .email
          Наша почта:
          - if action_name == 'landing'
            eyegaz@gmail.com
          - else
            = mail_to 'eyegaz@gmail.com'
      .clear
      .money-back
        На все услуги действует
        = link_to_unless action_name == 'landing', 'безусловная гарантия возврата денег', rules_path

  :plain
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
    (function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
    try {
    w.yaCounter25949792 = new Ya.Metrika({id:25949792,
    clickmap:true,
    trackLinks:true,
    accurateTrackBounce:true});
    } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
    s = d.createElement("script"),
    f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
    d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/25949792" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

app/views/layouts/_header.html.haml
%header
  .hat
    = link_to real_root_path do
      .logo
    .menu
      .item{ class: controller_name == 'parties' && 'active' || '' }
        = link_to all_parties_path do
          Ближайшие
          %br вечеринки
      .separator
      .item{ class: /recalls|albums/ =~ controller_name && 'active' || '' }
        = link_to recalls_path do
          Фото-видео
          %br отчёты
      .separator
      .item{ class: controller_name == 'pages' && !(/edit|rules/ =~ action_name) && 'active' || '' }
        = link_to structure_path do
          Что тебя
          %br ожидает
      .separator
      .item{ class: controller_name == 'articles' && 'active' || '' }
        = link_to articles_path do
          О зрительном
          %br контакте
      .separator
      .item{ class: controller_name == 'pages' && !(/edit|rules/ =~ action_name) && 'active' || '' }
        = link_to entities_path do
          Статьи
    - if admin_signed_in?
      .sign-out
        = link_to 'Выйти', destroy_admin_session_path, method: :delete
        = link_to 'Заявки', all_requests_path
        = link_to 'Страница информации', info_page_path

app/views/layouts/_page_description.html.haml
- provide :meta_description, @page.meta_description

.description-main
  %h1.title= @page.title
  .description
    = @page.content.html_safe unless @page.content.nil?
    .ps
      %p
        %span.left
        %i
          = @page.ps.html_safe unless @page.ps.nil?
- if admin_signed_in?
  .admin-links= link_to 'Редактировать описание', [:edit, @page]

app/views/layouts/_sidebar_only_group.html.haml
.sidebar
  .our-group
    = link_to 'http://vk.com/eyegazing' do
      .name.titleable Наша группа
      .vk
  - if controller_name != 'parties' && controller_name != 'payments'
    .button= link_to 'Участвовать в Свиданиях без Слов', all_parties_path
  - if action_name != 'landing'
    .subscrite-to-new-anonces= link_to 'Подписаться на анонсы новых вечеринок', root_path, target: '_blank'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title_for yield(:title)
    = stylesheet_link_tag     "application"
    = javascript_include_tag  "application"
    = yield :head
    = csrf_meta_tags
    = meta_description_for yield(:meta_description)

  %body
    .wrapper
      .bg-fill
        .fader
      = render 'layouts/header' unless controller_name == 'welcome' && action_name == 'landing'
      .flash{style: ( flash.empty? && '' || 'display: block; z-index: 1;' )}
        - unless flash.empty?
          .flash-body
            .text
              - flash.each do |name, msg|
                = content_tag :div, msg, class: "#{name} h4"
            .close.close-small
              .x
              .y
      .main{ role: 'main' }
        = yield
      .push
    = render 'layouts/footer'